# Generated by Django 5.2.5 on 2025-09-05 18:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-идентификатор')),
                ('company_type', models.CharField(choices=[('LLC', 'ООО'), ('IP', 'ИП'), ('JSC', 'АО'), ('CJSC', 'ЗАО'), ('OTHER', 'Другое')], max_length=20, verbose_name='Тип организации')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('country', models.CharField(default='Россия', max_length=100, verbose_name='Страна')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='ИНН')),
                ('registration_number', models.CharField(blank=True, max_length=50, verbose_name='ОГРН')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_companies', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/', verbose_name='Логотип')),
                ('theme_color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Цвет темы')),
                ('allow_user_registration', models.BooleanField(default=False, verbose_name='Разрешить регистрацию пользователей')),
                ('require_email_verification', models.BooleanField(default=True, verbose_name='Требовать подтверждение email')),
                ('default_currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта по умолчанию')),
                ('order_approval_required', models.BooleanField(default=True, verbose_name='Требовать одобрение заказов')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='companies.company')),
            ],
            options={
                'verbose_name': 'Настройки компании',
                'verbose_name_plural': 'Настройки компаний',
            },
        ),
        migrations.CreateModel(
            name='CompanyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('admin', 'Администратор'), ('manager', 'Менеджер'), ('employee', 'Сотрудник'), ('viewer', 'Наблюдатель')], default='employee', max_length=20, verbose_name='Роль')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='Может управлять пользователями')),
                ('can_manage_orders', models.BooleanField(default=False, verbose_name='Может управлять заказами')),
                ('can_manage_products', models.BooleanField(default=False, verbose_name='Может управлять товарами')),
                ('can_manage_suppliers', models.BooleanField(default=False, verbose_name='Может управлять поставщиками')),
                ('can_view_reports', models.BooleanField(default=False, verbose_name='Может просматривать отчеты')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активное членство')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата присоединения')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Членство в компании',
                'verbose_name_plural': 'Членства в компаниях',
                'unique_together': {('company', 'user')},
            },
        ),
    ]
