# Generated by Django 5.2.5 on 2025-09-21 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMenuSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название раздела')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('icon', models.CharField(choices=[('bi-people', 'Люди'), ('bi-cart', 'Корзина'), ('bi-box', 'Коробка'), ('bi-building', 'Здание'), ('bi-graph-up', 'График'), ('bi-calendar', 'Календарь'), ('bi-folder', 'Папка'), ('bi-gear', 'Настройки'), ('bi-file-text', 'Документ'), ('bi-chat', 'Чат'), ('bi-bell', 'Уведомления'), ('bi-shield', 'Безопасность'), ('bi-tools', 'Инструменты'), ('bi-pie-chart', 'Диаграмма'), ('bi-clipboard', 'Буфер'), ('bi-trophy', 'Трофей'), ('bi-star', 'Звезда'), ('bi-heart', 'Сердце'), ('bi-lightning', 'Молния'), ('bi-cloud', 'Облако')], default='bi-folder', max_length=50, verbose_name='Иконка')),
                ('section_type', models.CharField(choices=[('internal', 'Внутренний раздел'), ('external', 'Внешняя ссылка'), ('iframe', 'Встроенная страница')], default='internal', max_length=20, verbose_name='Тип раздела')),
                ('url', models.CharField(max_length=500, verbose_name='URL или путь')),
                ('order', models.PositiveIntegerField(default=100, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('open_in_new_tab', models.BooleanField(default=False, verbose_name='Открывать в новой вкладке')),
                ('required_role', models.CharField(choices=[('owner', 'Владелец'), ('admin', 'Администратор'), ('manager', 'Менеджер'), ('employee', 'Сотрудник'), ('viewer', 'Наблюдатель')], default='employee', max_length=20, verbose_name='Минимальная роль для доступа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_sections', to='companies.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_menu_sections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Раздел меню компании',
                'verbose_name_plural': 'Разделы меню компании',
                'ordering': ['order', 'title'],
                'unique_together': {('company', 'title')},
            },
        ),
    ]
